name: purge_pub_cache
description: Purge old package versions from pub-cache.
repository: https://github.com/masahiro-ikemoto/purge_pub_cache

version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.2.0
  pub_cache: ^0.3.0
  yaml: ^3.1.0

executables:
  purge_pub_cache:
